- name: PLAY-01
  hosts: web
  tasks:
  - name: PLAY-01 TASK-01
    ansible.builtin.debug:
      msg: " This is from PLAY-01 and TASK-01"

- name:
  hosts:
  tasks:
  - name:
    ansible.builtin.debug:
      msg: "This is from PLAY-02 and TASK-02"