- name: variables from files
  hosts: web 
  tasks:
  - name: Print the course info
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"