- name: check a number is less than 10 or not
  hosts: localhost
  connection: local
  vars_prompt:
  - name: my_number
    prompt: Please enter the number
    private: false
  tasks:
  - name: print this if less than 10
    ansible.builtin.debug:
      msg: "Given number {{ number }} is less than 10"
    when: number < 10  

  - name: print this if less than 10
    ansible.builtin.debug:
      msg: "Given number {{ number }} is less than 10"
    when: number >= 10    